# Generated by Django 4.2.6 on 2023-10-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("START", "START"), ("HELP", "HELP"), ("CENSOR", "CENSOR")], null=True, unique=True
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
    ]
