# Generated by Django 4.2.6 on 2023-10-05 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_telegramanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.IntegerField(default=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="generations_count",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="telegramanswer",
            name="type",
            field=models.CharField(
                choices=[("START", "START"), ("HELP", "HELP"), ("CENSOR", "CENSOR")], default=1, unique=True
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(unique=True)),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="referrer",
                    ),
                ),
            ],
        ),
    ]
