# Generated by Django 4.2.6 on 2023-10-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_user_chat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prompt", models.CharField()),
                ("chat_id", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
