# Generated by Django 4.2.6 on 2023-10-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_discordqueue_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordqueue",
            name="message_hash",
            field=models.CharField(default="asd"),
            preserve_default=False,
        ),
    ]
