# Generated by Django 4.2.6 on 2023-10-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_discordqueue_message_hash"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discordqueue",
            old_name="chat_id",
            new_name="telegram_chat_id",
        ),
        migrations.AddField(
            model_name="discordqueue",
            name="discord_message_id",
            field=models.CharField(null=True),
        ),
    ]
