# Generated by Django 4.2.6 on 2023-10-13 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import main.enums


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_rename_chat_id_discordqueue_telegram_chat_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordqueue",
            name="telegram_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "ADMIN"), ("PREMIUM", "PREMIUM"), ("BASE", "BASE")],
                default=main.enums.UserRoleEnum["BASE"],
            ),
        ),
    ]
