# Generated by Django 4.2.6 on 2023-10-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordqueue",
            name="telegram_chat_id",
            field=models.CharField(null=True),
        ),
    ]
