# Generated by Django 4.2.6 on 2023-10-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_discordqueue_telegram_chat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MjUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(unique=True)),
                ("is_banned", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name="DiscordQueue",
            new_name="Prompt",
        ),
    ]
