# Generated by Django 4.2.6 on 2023-10-16 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_mjuser_rename_discordqueue_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="telegram_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="prompts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
