# Generated by Django 4.2.6 on 2023-10-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_pay"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
