# Generated by Django 4.2.6 on 2023-10-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_referral_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="parent_id",
            field=models.IntegerField(null=True),
        ),
    ]
