# Generated by Django 4.2.6 on 2023-10-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_prompt_parent_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="parent_id",
        ),
        migrations.AddField(
            model_name="prompt",
            name="action",
            field=models.CharField(null=True),
        ),
    ]
