# Generated by Django 4.2.6 on 2023-10-21 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_rename_action_prompt_caption"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MjUser",
        ),
    ]
