# Generated by Django 4.2.6 on 2023-10-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_delete_mjuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Describe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_name", models.CharField()),
                ("chat_id", models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(null=True, unique=True),
        ),
    ]
