# Generated by Django 4.2.6 on 2023-10-27 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_describe_alter_user_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.CharField()),
                ("uploaded_filename", models.CharField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="blends", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
