# Generated by Django 4.2.6 on 2023-10-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_blend"),
    ]

    operations = [
        migrations.AddField(
            model_name="blend",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="describe",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
