# Generated by Django 4.2.6 on 2023-10-28 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_blend_created_at_describe_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="generations_count",
            new_name="balance",
        ),
    ]
