# Generated by Django 4.2.6 on 2023-10-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_rename_generations_count_user_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referral",
            name="is_active",
        ),
        migrations.AddField(
            model_name="referral",
            name="used_count",
            field=models.IntegerField(default=0),
        ),
    ]
