# Generated by Django 4.2.6 on 2023-10-30 16:32

from django.db import migrations, models

import main.enums


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_gptcontext"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("READY", "READY")], default=main.enums.UserRoleEnum["BASE"]
            ),
        ),
    ]
