# Generated by Django 4.2.6 on 2023-10-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0026_user_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
