# Generated by Django 4.2.6 on 2023-10-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_referral_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pay",
            name="item",
        ),
        migrations.AddField(
            model_name="pay",
            name="is_verified",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="pay",
            name="pay_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pay",
            name="token_count",
            field=models.IntegerField(null=True),
        ),
    ]
