# Generated by Django 4.2.6 on 2023-10-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_remove_pay_item_pay_is_verified_pay_pay_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blend",
            name="last_message_id",
            field=models.CharField(null=True),
        ),
    ]
