# Generated by Django 4.2.6 on 2023-11-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_blend_last_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pay",
            name="pay_id",
            field=models.CharField(null=True),
        ),
    ]
