# Generated by Django 4.2.6 on 2023-11-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_alter_pay_pay_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.IntegerField(default=15),
        ),
    ]
