# Generated by Django 4.2.6 on 2023-11-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0031_alter_user_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="chat_id",
            field=models.CharField(null=True, unique=True),
        ),
    ]
