# Generated by Django 4.2.6 on 2023-11-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0032_referral_created_at_alter_user_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="blend",
            name="chat_id",
            field=models.CharField(null=True),
        ),
    ]
