# Generated by Django 4.2.6 on 2023-11-04 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import main.enums


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0034_pay_merchant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(verbose_name="Колличество")),
                (
                    "product",
                    models.CharField(
                        choices=[("TOKEN", "TOKEN")], default=main.enums.ProductEnum["TOKEN"], verbose_name="Продукт"
                    ),
                ),
                ("description", models.CharField(verbose_name="Описание")),
                ("amount", models.FloatField(verbose_name="Сумма")),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "RUB"), ("USD", "USD")],
                        default=main.enums.CurrencyEnum["RUB"],
                        verbose_name="Валюта",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активный")),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AlterModelOptions(
            name="banword",
            options={"verbose_name": "Запрещенное слово", "verbose_name_plural": "Запрещенные слова"},
        ),
        migrations.AlterModelOptions(
            name="blend",
            options={"verbose_name": "Объедененное фото", "verbose_name_plural": "Объедененные фото"},
        ),
        migrations.AlterModelOptions(
            name="describe",
            options={"verbose_name": "Описание фото", "verbose_name_plural": "Описания фото"},
        ),
        migrations.AlterModelOptions(
            name="gptcontext",
            options={"verbose_name": "Контекст GPT", "verbose_name_plural": "Контексты GPT"},
        ),
        migrations.AlterModelOptions(
            name="pay",
            options={"verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
        migrations.AlterModelOptions(
            name="prompt",
            options={"verbose_name": "Промпт", "verbose_name_plural": "Промпты"},
        ),
        migrations.AlterModelOptions(
            name="referral",
            options={"verbose_name": "Рефферальная ссылка", "verbose_name_plural": "Реферальные ссылки"},
        ),
        migrations.AlterModelOptions(
            name="telegramanswer",
            options={"verbose_name": "Ответ бота", "verbose_name_plural": "Ответы бота"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
        migrations.RemoveField(
            model_name="blend",
            name="last_message_id",
        ),
        migrations.AlterField(
            model_name="banword",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активный"),
        ),
        migrations.AlterField(
            model_name="banword",
            name="word",
            field=models.CharField(unique=True, verbose_name="Запрещенное слово"),
        ),
        migrations.AlterField(
            model_name="blend",
            name="chat_id",
            field=models.CharField(null=True, verbose_name="ID телеграм чата"),
        ),
        migrations.AlterField(
            model_name="blend",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Время создания"),
        ),
        migrations.AlterField(
            model_name="blend",
            name="group_id",
            field=models.CharField(verbose_name="ID медиа группы"),
        ),
        migrations.AlterField(
            model_name="blend",
            name="uploaded_filename",
            field=models.CharField(verbose_name="Имя файла"),
        ),
        migrations.AlterField(
            model_name="blend",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blends",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="describe",
            name="chat_id",
            field=models.CharField(verbose_name="ID телеграм чата"),
        ),
        migrations.AlterField(
            model_name="describe",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Время создания"),
        ),
        migrations.AlterField(
            model_name="describe",
            name="file_name",
            field=models.CharField(verbose_name="Имя файла"),
        ),
        migrations.AlterField(
            model_name="gptcontext",
            name="content",
            field=models.CharField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="gptcontext",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Время создания"),
        ),
        migrations.AlterField(
            model_name="gptcontext",
            name="role",
            field=models.CharField(verbose_name="Роль"),
        ),
        migrations.AlterField(
            model_name="gptcontext",
            name="telegram_chat_id",
            field=models.CharField(verbose_name="ID телеграм чата"),
        ),
        migrations.AlterField(
            model_name="gptcontext",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gpt_contexts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="pay",
            name="amount",
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Сумма оплаты"),
        ),
        migrations.AlterField(
            model_name="pay",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Время создания"),
        ),
        migrations.AlterField(
            model_name="pay",
            name="is_verified",
            field=models.BooleanField(default=False, null=True, verbose_name="Подтвержден"),
        ),
        migrations.AlterField(
            model_name="pay",
            name="merchant",
            field=models.CharField(
                choices=[("YOOKASSA", "YOOKASSA"), ("WALLET", "WALLET")], null=True, verbose_name="Провайдер"
            ),
        ),
        migrations.AlterField(
            model_name="pay",
            name="pay_id",
            field=models.CharField(null=True, verbose_name="ID оплаты в провайдере"),
        ),
        migrations.AlterField(
            model_name="pay",
            name="token_count",
            field=models.IntegerField(null=True, verbose_name="Эквивалент в токенах"),
        ),
        migrations.AlterField(
            model_name="pay",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="caption",
            field=models.CharField(null=True, verbose_name="Подпись"),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Время создания"),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="discord_message_id",
            field=models.CharField(null=True, verbose_name="ID сообщения в дискорд"),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="message_hash",
            field=models.CharField(null=True, verbose_name="хэш сообщения"),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="prompt",
            field=models.CharField(verbose_name="Промпт или действие"),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="telegram_chat_id",
            field=models.CharField(null=True, verbose_name="ID телеграм чата"),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="telegram_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Время создания"),
        ),
        migrations.AlterField(
            model_name="referral",
            name="key",
            field=models.CharField(unique=True, verbose_name="Уникальный ключ"),
        ),
        migrations.AlterField(
            model_name="referral",
            name="name",
            field=models.CharField(blank=True, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="referral",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец ссылки",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="used_count",
            field=models.IntegerField(default=0, verbose_name="Колличество переходов"),
        ),
        migrations.AlterField(
            model_name="telegramanswer",
            name="message",
            field=models.TextField(verbose_name="Содержание ответа"),
        ),
        migrations.AlterField(
            model_name="telegramanswer",
            name="type",
            field=models.CharField(
                choices=[("START", "START"), ("HELP", "HELP"), ("CENSOR", "CENSOR")],
                unique=True,
                verbose_name="Тип ответа",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.IntegerField(default=15, verbose_name="Баланс в токенах"),
        ),
        migrations.AlterField(
            model_name="user",
            name="chat_id",
            field=models.CharField(null=True, unique=True, verbose_name="ID чата телеграм"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, verbose_name="Пароль"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "ADMIN"), ("PREMIUM", "PREMIUM"), ("BASE", "BASE")],
                default=main.enums.UserRoleEnum["BASE"],
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("READY", "READY")],
                default=main.enums.UserRoleEnum["BASE"],
                verbose_name="Состояние",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(null=True, unique=True, verbose_name="Юзернейм в телеграме"),
        ),
    ]
