# Generated by Django 4.2.6 on 2023-11-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0036_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(verbose_name="Канал")),
            ],
            options={
                "verbose_name": "Канал",
                "verbose_name_plural": "Каналы",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, null=True),
        ),
    ]
