# Generated by Django 4.2.6 on 2023-11-06 12:24

from django.db import migrations, models

import main.enums


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0039_user_telegram_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_user_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("READY", "READY")],
                default=main.enums.UserStateEnum["READY"],
                verbose_name="Состояние",
            ),
        ),
    ]
