# Generated by Django 4.2.6 on 2023-11-06 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0041_user_telegram_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_user_id",
        ),
    ]
