# Generated by Django 4.2.6 on 2023-11-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0042_remove_user_telegram_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DsMjUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, null=True, verbose_name="Имя")),
                ("token", models.CharField(unique=True, verbose_name="Токен")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активный")),
            ],
            options={
                "verbose_name": "Дискорд аккаунт",
                "verbose_name_plural": "Дискорд аккаунты",
            },
        ),
    ]
