# Generated by Django 4.2.6 on 2023-11-06 19:19

from django.db import migrations, models
import main.enums


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0043_dsmjuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsmjuser",
            name="fail_in_row",
            field=models.IntegerField(default=0, verbose_name="Ошибок подряд"),
        ),
        migrations.AddField(
            model_name="user",
            name="fail_in_row",
            field=models.IntegerField(default=0, verbose_name="Ошибок подряд"),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("READY", "READY"), ("BANNED", "BANNED")],
                default=main.enums.UserStateEnum["READY"],
                verbose_name="Состояние",
            ),
        ),
    ]
