# Generated by Django 4.2.6 on 2023-11-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0044_dsmjuser_fail_in_row_user_fail_in_row_user_gen_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pay_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата последней оплаты"),
        ),
    ]
