# Generated by Django 4.2.6 on 2023-11-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0045_alter_user_pay_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_state_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ожидает с"),
        ),
    ]
