# Generated by Django 4.2.6 on 2023-11-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0046_alter_user_invited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gen_date",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Дата последней генерации"),
        ),
        migrations.AddField(
            model_name="user",
            name="pay_date",
            field=models.DateTimeField(null=True, verbose_name="Дата последней оплаты"),
        ),
    ]
