# Generated by Django 4.2.6 on 2023-11-09 00:31

from django.db import migrations, models

import main.enums


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0046_user_pending_state_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("IMAGINE", "imagine"),
                            ("DESCRIBE", "describe"),
                            ("VARY", "vary"),
                            ("ZOOM", "zoom"),
                            ("PAN", "pan"),
                            ("DESCRIBE_RETRY", "describe_retry"),
                            ("UPSAMPLE", "upsample"),
                            ("VARIATION", "variation"),
                            ("REROLL", "reroll"),
                            ("UPSCALE_2_X", "upscale__v5_2x"),
                            ("UPSCALE_4_X", "upscale__v5_4x"),
                            ("DALLE", "dalle"),
                            ("GPT", "gpt"),
                        ],
                        verbose_name="Опция",
                    ),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "RUB"), ("USD", "USD")],
                        default=main.enums.CurrencyEnum["RUB"],
                        verbose_name="Валюта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена",
                "verbose_name_plural": "Цены",
            },
        ),
        migrations.AlterField(
            model_name="telegramanswer",
            name="type",
            field=models.CharField(
                choices=[
                    ("START", "START"),
                    ("HELP", "HELP"),
                    ("CENSOR", "CENSOR"),
                    ("GPT_OPTION", "GPT_OPTION"),
                    ("PRICES", "PRICES"),
                    ("UPSCALE_CONFIRM", "UPSCALE_CONFIRM"),
                    ("GPT_PRICE", "GPT_PRICE"),
                ],
                unique=True,
                verbose_name="Тип ответа",
            ),
        ),
    ]
