# Generated by Django 4.2.6 on 2023-11-09 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0047_optionprice_alter_telegramanswer_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="optionprice",
            name="currency",
        ),
    ]
