# Generated by Django 4.2.6 on 2023-11-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0048_remove_optionprice_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionprice",
            name="price",
            field=models.IntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="optionprice",
            name="product",
            field=models.CharField(
                choices=[
                    ("imagine", "imagine"),
                    ("describe", "describe"),
                    ("vary", "vary"),
                    ("zoom", "zoom"),
                    ("pan", "pan"),
                    ("describe_retry", "describe_retry"),
                    ("upsample", "upsample"),
                    ("variation", "variation"),
                    ("reroll", "reroll"),
                    ("upscale__v5_2x", "upscale__v5_2x"),
                    ("upscale__v5_4x", "upscale__v5_4x"),
                    ("dalle", "dalle"),
                    ("gpt", "gpt"),
                ],
                verbose_name="Опция",
            ),
        ),
    ]
