# Generated by Django 4.2.6 on 2023-11-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0049_alter_optionprice_price_alter_optionprice_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="link",
            field=models.CharField(
                default=1, help_text="Ссылка, прикрепляемая к кнопке", verbose_name="Ссылка на канал"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="channel",
            name="channel",
            field=models.CharField(
                help_text="В телеграме обозначается как @Имя_канала, <@> указывать не надо", verbose_name="Имя канала"
            ),
        ),
    ]
