# Generated by Django 4.2.6 on 2023-11-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0050_channel_link_alter_channel_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(blank=True, null=True, unique=True, verbose_name="Юзернейм в телеграме"),
        ),
    ]
