# Generated by Django 4.2.6 on 2023-11-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0051_alter_user_telegram_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="label",
            field=models.CharField(
                help_text="Это поле будет отображаться на кнопке", null=True, verbose_name="Имя канала"
            ),
        ),
        migrations.AlterField(
            model_name="optionprice",
            name="product",
            field=models.CharField(
                choices=[
                    ("imagine", "imagine"),
                    ("blend", "blend"),
                    ("describe", "describe"),
                    ("vary", "vary"),
                    ("zoom", "zoom"),
                    ("pan", "pan"),
                    ("describe_retry", "describe_retry"),
                    ("upsample", "upsample"),
                    ("variation", "variation"),
                    ("reroll", "reroll"),
                    ("upscale__v5_2x", "upscale__v5_2x"),
                    ("upscale__v5_4x", "upscale__v5_4x"),
                    ("dalle", "dalle"),
                    ("gpt", "gpt"),
                ],
                verbose_name="Опция",
            ),
        ),
    ]
