# Generated by Django 4.2.6 on 2023-11-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0052_channel_label_alter_optionprice_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="label",
            field=models.CharField(
                help_text="Это поле будет отображаться на кнопке", null=True, verbose_name="Название канала"
            ),
        ),
    ]
