# Generated by Django 4.2.6 on 2023-11-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0053_alter_channel_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_subscribed",
            field=models.BooleanField(default=False, verbose_name="Был подписан на все каналы"),
        ),
    ]
