# Generated by Django 4.2.6 on 2023-12-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0057_dsmjuser_proxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="chat_id",
            field=models.CharField(blank=True, null=True, unique=True, verbose_name="ID чата телеграм"),
        ),
    ]
